[package]
name = "base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
monch.workspace = true
once_cell.workspace = true
deno_semver.workspace = true
deno_npm.workspace = true
cpu_timer = { version = "0.1.0", path = "../cpu_timer" }
anyhow = { workspace = true }
bytes = { version = "1.2.1" }
cityhash = { version = "0.1.1" }
deno_ast = { workspace = true }
deno_fs.workspace = true
deno_io = { workspace = true }
deno_core = { workspace = true }
deno_console = { workspace = true }
deno_crypto = { workspace = true }
deno_fetch = { workspace = true }
deno_http = { workspace = true }
deno_net = { workspace = true }
deno_url = { workspace = true }
deno_tls = { workspace = true }
deno_webidl = { workspace = true }
deno_web = { workspace = true }
deno_websocket = { workspace = true }
httparse = { version = "1.8.0" }
hyper = { version = "0.14.26", features = ["full"] }
http = { version = "0.2" }
import_map.workspace = true
log = { workspace = true }
reqwest.workspace = true
serde = { version = "1.0.149", features = ["derive"] }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
futures-util = { workspace = true }
url = { version = "2.3.1" }
event_worker = { version = "0.1.0", path = "../event_worker" }
sb_workers = { version = "0.1.0", path = "../sb_workers" }
sb_env = { version = "0.1.0", path = "../sb_env" }
sb_core = { version = "0.1.0", path = "../sb_core" }
sb_os = { version = "0.1.0", path = "../sb_os" }
sb_npm = { version = "0.1.0", path = "../npm" }
sb_graph = { version = "0.1.0", path = "../sb_graph" }
sb_module_loader = { version = "0.1.0", path = "../sb_module_loader" }
uuid = { workspace = true }
deno_broadcast_channel.workspace = true
sb_node = { version = "0.1.0", path = "../node" }
eszip.workspace = true
notify = { version = "6.1.1", default-features = false, features = [
    "macos_kqueue",
] }
flume = { version = "0.11.0" }
enum-as-inner.workspace = true
urlencoding.workspace = true
scopeguard = { version = "1.2.0" }
pin-project = { version = "1.1.3" }
ctor = { workspace = true }

[dev-dependencies]
flaky_test = { version = "0.1.0", path = "../flaky_test" }
serial_test = { version = "3.0.0" }

[build-dependencies]
sb_core = { version = "0.1.0", path = "../sb_core" }
sb_npm = { version = "0.1.0", path = "../npm" }
sb_graph = { version = "0.1.0", path = "../sb_graph" }
sb_workers = { version = "0.1.0", path = "../sb_workers" }
sb_env = { version = "0.1.0", path = "../sb_env" }
sb_os = { version = "0.1.0", path = "../sb_os" }
sb_node = { version = "0.1.0", path = "../node" }
anyhow = { workspace = true }
bytes = { version = "1.2.1" }
deno_ast = { workspace = true }
deno_fs.workspace = true
deno_io = { workspace = true }
deno_core = { workspace = true }
deno_console = { workspace = true }
deno_crypto = { workspace = true }
deno_fetch = { workspace = true }
deno_http = { workspace = true }
deno_net = { workspace = true }
deno_url = { workspace = true }
deno_tls = { workspace = true }
deno_webidl = { workspace = true }
deno_web = { workspace = true }
deno_websocket = { workspace = true }
httparse = { version = "1.8.0" }
hyper = { version = "0.14.26", features = ["full"] }
http = { version = "0.2" }
log = { workspace = true }
reqwest.workspace = true
serde = { version = "1.0.149", features = ["derive"] }
tokio.workspace = true
url = { version = "2.3.1" }
event_worker = { version = "0.1.0", path = "../event_worker" }
deno_broadcast_channel.workspace = true
